name: 'Get JIRA Ticket Title'
description: 'Get the JIRA ticket title from the JIRA API'
inputs:
  jira_base_url: ${{ secrets.JIRA_BASE_URL }}
  jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
  jira_email: ${{ secrets.JIRA_EMAIL }}
  jira_ticket:
    description: 'The JIRA ticket ID'
    required: true
outputs:
  jira_title:
    description: 'The JIRA ticket title'
runs:
  using: 'node12'
  main: 'index.js'
