name: 'Get JIRA Ticket Title'
description: 'Get the JIRA ticket title from the JIRA API'
inputs:
  jira_ticket:
    description: 'The JIRA ticket ID'
    required: true
  jira_base_url:
    description: 'The base URL of the JIRA instance'
    required: true
  jira_api_token:
    description: 'The JIRA API token'
    required: true
  jira_email:
    description: 'The email associated with the JIRA account'
    required: true
outputs:
  jira_title:
    description: 'The JIRA ticket title'
runs:
  using: 'node12'
  main: 'index.js'